export enum InfluenceType {
  DATA_EXCHANGE,
  DISTRIBUTED_COMPUTING,
  PERFORMANCE,
  HIGH_USE,
  TRANSACTION_VOLUME,
  ONLINE_DATA_INPUT,
  END_USER_EFICIENCY,
  ONLINE_UPDATES,
  COMPLEX_PROCESSING,
  REUSABILITY,
  EASE_OF_INSTALLATION,
  EASE_OF_USE,
  MULTIPLE_PROCESSING_SITES,
  EASE_OF_CHANGES
}
